name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose
      - name: Lint
        uses: giraffate/clippy-action@v1
      - name: Tests
        run: cargo test --verbose
      - name: Cargo check
        run: cargo check
      - name: Build (no features)
        run: cargo build --verbose --no-default-features
